---
title: "SDOH Variables Table"
author: "Shelby Level"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

| Variable Name                | Description                                                                                                           |
|:-----------------|:-----------------------------------------------------|
| ACS_PCT_CHILD_DISAB          | Percentage of children with a disability (ages 17 and below)                                                          |
| ACS_PCT_DISABLE              | Percentage of population with a disability                                                                            |
| ACS_PCT_HH_NO_INTERNET       | ACS_PCT_HH_NO_INTERNET                                                                                                |
| ACS_PCT_HH_NO_COMP_DEV       | ACS_PCT_HH_NO_COMP_DEV                                                                                                |
| ACS_PCT_EMPLOYED             | Percentage of civilian labor force that is employed (ages 16 and over)                                                |
| ACS_PCT_NOT_LABOR            | Percentage of population not in labor force (ages 16 and over)                                                        |
| ACS_MEDIAN_HH_INC            | Median household income (dollars, inflation-adjusted to data file year)                                               |
| ACS_PCT_NONVET_POV_18_64     | Percentage of civilian nonveterans with income below the poverty level in the past 12 months (between ages 18 and 64) |
| ACS_PCT_PERSON_INC_BELOW99   | Percentage of population with an income to poverty ratio under 1.00                                                   |
| ACS_PCT_INC50                | Percentage of population with income to poverty ratio under 0.50                                                      |
| ACS_PCT_LT_HS                | Percentage of population with less than high school education (ages 25 and over)                                      |
| ACS_PCT_HU_MOBILE_HOME       | Percentage of housing units that are mobile homes                                                                     |
| ACS_PCT_OWNER_HU_COST_50PCT  | Percentage of owner-occupied housing units with rent equal to 50 percent or more of household income                  |
| ACS_PCT_RENTER_HU_COST_50PCT | Percentage of renter-occupied housing units with rent equal to 50 percent or more of household income                 |
| ACS_PCT_WORK_NO_CAR          | Percentage of workers in households with no vehicle available (ages 16 and over)                                      |
| ACS_PCT_UNINSURED_BELOW64    | Percentage of population with no health insurance (ages 64 and below)                                                 |
| POS_DIST_CLINIC_TRACT        | Distance in miles to the nearest health clinic (FQHC, RHC), calculated using population weighted tract centroids      |

No chronic health data available
